# /opt/docker/config/traefik/traefik.yml
api:
  dashboard: true
  insecure: true  # Allow dashboard on :8080 without HTTPS

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@home.lab
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG  # Increased logging for troubleshooting
  filePath: /data/traefik.log

accessLog:
  filePath: /data/access.log
