services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      - infrastructure_traefik
      - infrastructure_database
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "2222:22"
      - "3000:3000"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.home.lab`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.docker.network=infrastructure_traefik"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: unless-stopped
    networks:
      - infrastructure_traefik
      - infrastructure_database
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN_FILE=/run/secrets/gitea_runner_token
      - GITEA_RUNNER_NAME=docker-01-runner
      - GITEA_RUNNER_LABELS=ubuntu-latest,docker,homelab
    volumes:
      - gitea_runner_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker:/opt/docker:ro
    secrets:
      - gitea_runner_token
    depends_on:
      - gitea
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep act_runner || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    profiles:
      - runner  # Won't start until we have the token

include:
  - filebrowser.yml
  - syncthing.yml
  - wikijs.yml
  - memos.yml
  - immich.yml
  - jellyfin.yml

networks:
  infrastructure_traefik:
    external: true
  infrastructure_database:
    external: true

volumes:
  gitea_data:
    driver: local
  gitea_runner_data:
    driver: local

secrets:
  gitea_runner_token:
    file: /opt/docker/secrets/gitea_runner_token.txt
